In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
titles = []
prices = []
ratings = []
availability = []

In [ ]:
for page in range(1,26):

    url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    response = requests.get(url)

    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:

        # title
        title = book.h3.a["title"]

        # price
        price = book.find("p", class_="price_color").text

        # rating
        rating = book.p["class"][1]

        # availability
        stock = book.find("p", class_="instock availability").text.strip()

        titles.append(title)
        prices.append(price)
        ratings.append(rating)
        availability.append(stock)

In [ ]:
data = pd.DataFrame({
    "Title": titles,
    "Price": prices,
    "Rating": ratings,
    "Availability": availability
})

data.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [ ]:
print(data.shape)

(500, 4)

In [ ]:
data.to_csv("books_500_dataset.csv", index=False)

In [ ]:
data.tail()

,Title,Price,Rating,Availability
495,Unreasonable Hope: Finding Faith in the God Wh...,Â£46.33,Two,In stock
496,Under the Tuscan Sun,Â£37.33,Three,In stock
497,Toddlers Are A**holes: It's Not Your Fault,Â£25.55,One,In stock
498,The Year of Living Biblically: One Man's Humbl...,Â£34.72,One,In stock
499,The Whale,Â£35.96,Four,In stock

In [ ]:
len(data)

500